### ISSUE TITLE
OpenID Library

### ISSUE THREAD

**Issue by lancepioch** [hardwiregaming/community#8]
Currently we're using SteamOpenIDInfo.php

Is this the best solution? This is what I used before: https://packagist.org/packages/iignatov/lightopenid

And finally:
![image](https://cloud.githubusercontent.com/assets/1296882/10763439/51421f8a-7ca0-11e5-8ffb-519ce20db21c.png)

**Comment by arcdigital** [comment]
I'm fine using a different library, but maybe make this low priority?

**Comment by lancepioch** [comment]
Found a nice new library, it works perfectly: https://github.com/invisnik/laravel-steam-auth

    "invisnik/laravel-steam-auth": "2.*"

**Comment by lancepioch** [comment]
I've replaced it in the dev branch.
